"""empty message

Revision ID: 4770db908610
Revises: 72c74a25b104
Create Date: 2021-12-12 19:56:28.108957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4770db908610'
down_revision = '72c74a25b104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('course', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column('telephone', sa.String(length=20), nullable=True))
    op.add_column('member', sa.Column('email', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=False)
    op.create_index(op.f('ix_member_telephone'), 'member', ['telephone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_telephone'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_column('member', 'email')
    op.drop_column('member', 'telephone')
    op.drop_column('course', 'duration')
    op.drop_column('course', 'date_start')
    # ### end Alembic commands ###
