"""empty message

Revision ID: 61c92b0f191e
Revises: e324f6df5289
Create Date: 2021-12-14 22:57:50.756202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c92b0f191e'
down_revision = 'e324f6df5289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('member', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('member', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teacher', 'surname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('teacher', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('teacher', 'patronymic',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'patronymic',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('teacher', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('teacher', 'surname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('member', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('member', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('member', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
