"""empty message

Revision ID: b698a76bea4c
Revises: c262d440f2b5
Create Date: 2021-12-13 19:55:30.840271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b698a76bea4c'
down_revision = 'c262d440f2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'teacher_id')
    # ### end Alembic commands ###
