"""empty message

Revision ID: c262d440f2b5
Revises: 4770db908610
Create Date: 2021-12-13 19:46:44.584348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c262d440f2b5'
down_revision = '4770db908610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_teacher_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('course_teacher_id_fkey', 'course', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
